-- CreateEnum
CREATE TYPE "CalendarEventType" AS ENUM ('semester_start', 'semester_end', 'holiday', 'first_term_start', 'first_term_end', 'second_term_start', 'second_term_end', 'exam_preparation', 'exam_start', 'exam_end', 'result_publication', 'supplementary_exam', 'college_event', 'meeting', 'other');

-- CreateEnum
CREATE TYPE "NoticeType" AS ENUM ('holiday_notice', 'exam_notice', 'result_notice', 'class_start_notice', 'general_notice');

-- CreateEnum
CREATE TYPE "ExamStatus" AS ENUM ('scheduled', 'ongoing', 'completed', 'cancelled', 'result_published');

-- CreateEnum
CREATE TYPE "ResultStatus" AS ENUM ('pending', 'draft', 'verified', 'published', 're_evaluation', 'final');

-- CreateEnum
CREATE TYPE "ExamCategory" AS ENUM ('regular', 'supplementary');

-- CreateEnum
CREATE TYPE "ExamTypeStatus" AS ENUM ('active', 'inactive', 'archived');

-- AlterTable
ALTER TABLE "CalendarEvent" ALTER COLUMN "isRecurring" SET DEFAULT false;

-- CreateTable
CREATE TABLE "AcademicCalendar" (
    "id" SERIAL NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "description" TEXT NOT NULL,
    "eventType" "CalendarEventType" NOT NULL,
    "semester" "Semester",
    "batchId" INTEGER,
    "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "isTermExam" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "AcademicCalendar_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "CalendarNotice" (
    "id" SERIAL NOT NULL,
    "calendarId" INTEGER NOT NULL,
    "noticeType" "NoticeType" NOT NULL,
    "title" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "generatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "CalendarNotice_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "terminal_configs" (
    "id" SERIAL NOT NULL,
    "batchId" INTEGER NOT NULL,
    "termCount" INTEGER NOT NULL DEFAULT 2,
    "termWeeks" TEXT NOT NULL DEFAULT '[7, 12]',
    "examDays" INTEGER NOT NULL DEFAULT 5,
    "semesterDuration" INTEGER NOT NULL DEFAULT 16,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "terminal_configs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ExamType" (
    "id" SERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "description" TEXT,
    "status" "ExamTypeStatus" NOT NULL DEFAULT 'active',
    "weightage" DOUBLE PRECISION,
    "isGraded" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ExamType_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Exam" (
    "id" SERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "examTypeId" INTEGER NOT NULL,
    "academicYear" TEXT,
    "semester" "Semester",
    "date" TIMESTAMP(3),
    "startTime" TIMESTAMP(3),
    "endTime" TIMESTAMP(3),
    "status" "ExamStatus" NOT NULL DEFAULT 'scheduled',
    "departmentId" INTEGER,
    "batchId" INTEGER,
    "classroomId" INTEGER,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Exam_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Result" (
    "id" SERIAL NOT NULL,
    "studentId" INTEGER NOT NULL,
    "classroomId" INTEGER,
    "examId" INTEGER,
    "examTypeId" INTEGER,
    "courseId" INTEGER,
    "examCategory" "ExamCategory" NOT NULL DEFAULT 'regular',
    "attempt" INTEGER,
    "semester" "Semester",
    "theoryMarks" DOUBLE PRECISION,
    "practicalMarks" DOUBLE PRECISION,
    "totalMarks" DOUBLE PRECISION,
    "maxMarks" DOUBLE PRECISION DEFAULT 100,
    "passMarks" DOUBLE PRECISION DEFAULT 40,
    "grade" TEXT,
    "gradePoint" DOUBLE PRECISION,
    "resultStatus" "ResultStatus" NOT NULL DEFAULT 'pending',
    "remarks" TEXT,
    "isAbsent" BOOLEAN NOT NULL DEFAULT false,
    "isPassed" BOOLEAN,
    "examRollNumber" TEXT,
    "resultDate" TIMESTAMP(3),
    "enteredBy" INTEGER,
    "verifiedBy" INTEGER,
    "verifiedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Result_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "AcademicCalendar_date_idx" ON "AcademicCalendar"("date");

-- CreateIndex
CREATE INDEX "AcademicCalendar_eventType_idx" ON "AcademicCalendar"("eventType");

-- CreateIndex
CREATE INDEX "AcademicCalendar_batchId_idx" ON "AcademicCalendar"("batchId");

-- CreateIndex
CREATE UNIQUE INDEX "terminal_configs_batchId_key" ON "terminal_configs"("batchId");

-- CreateIndex
CREATE UNIQUE INDEX "ExamType_name_key" ON "ExamType"("name");

-- CreateIndex
CREATE UNIQUE INDEX "ExamType_code_key" ON "ExamType"("code");

-- CreateIndex
CREATE INDEX "Exam_examTypeId_idx" ON "Exam"("examTypeId");

-- CreateIndex
CREATE INDEX "Exam_departmentId_idx" ON "Exam"("departmentId");

-- CreateIndex
CREATE INDEX "Exam_batchId_idx" ON "Exam"("batchId");

-- CreateIndex
CREATE INDEX "Exam_classroomId_idx" ON "Exam"("classroomId");

-- CreateIndex
CREATE INDEX "Exam_semester_idx" ON "Exam"("semester");

-- CreateIndex
CREATE INDEX "Exam_status_idx" ON "Exam"("status");

-- CreateIndex
CREATE INDEX "Result_studentId_idx" ON "Result"("studentId");

-- CreateIndex
CREATE INDEX "Result_examId_idx" ON "Result"("examId");

-- CreateIndex
CREATE INDEX "Result_classroomId_idx" ON "Result"("classroomId");

-- CreateIndex
CREATE INDEX "Result_resultStatus_idx" ON "Result"("resultStatus");

-- CreateIndex
CREATE INDEX "Result_examCategory_idx" ON "Result"("examCategory");

-- CreateIndex
CREATE INDEX "Result_semester_idx" ON "Result"("semester");

-- CreateIndex
CREATE INDEX "Result_attempt_idx" ON "Result"("attempt");

-- CreateIndex
CREATE INDEX "Result_examTypeId_idx" ON "Result"("examTypeId");

-- CreateIndex
CREATE INDEX "Result_courseId_idx" ON "Result"("courseId");

-- CreateIndex
CREATE UNIQUE INDEX "Result_studentId_courseId_examCategory_attempt_key" ON "Result"("studentId", "courseId", "examCategory", "attempt");

-- AddForeignKey
ALTER TABLE "AcademicCalendar" ADD CONSTRAINT "AcademicCalendar_batchId_fkey" FOREIGN KEY ("batchId") REFERENCES "Batch"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CalendarNotice" ADD CONSTRAINT "CalendarNotice_calendarId_fkey" FOREIGN KEY ("calendarId") REFERENCES "AcademicCalendar"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "terminal_configs" ADD CONSTRAINT "terminal_configs_batchId_fkey" FOREIGN KEY ("batchId") REFERENCES "Batch"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Exam" ADD CONSTRAINT "Exam_examTypeId_fkey" FOREIGN KEY ("examTypeId") REFERENCES "ExamType"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Exam" ADD CONSTRAINT "Exam_departmentId_fkey" FOREIGN KEY ("departmentId") REFERENCES "departments"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Exam" ADD CONSTRAINT "Exam_batchId_fkey" FOREIGN KEY ("batchId") REFERENCES "Batch"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Exam" ADD CONSTRAINT "Exam_classroomId_fkey" FOREIGN KEY ("classroomId") REFERENCES "Classroom"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Result" ADD CONSTRAINT "Result_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "Student"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Result" ADD CONSTRAINT "Result_classroomId_fkey" FOREIGN KEY ("classroomId") REFERENCES "Classroom"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Result" ADD CONSTRAINT "Result_examId_fkey" FOREIGN KEY ("examId") REFERENCES "Exam"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Result" ADD CONSTRAINT "Result_examTypeId_fkey" FOREIGN KEY ("examTypeId") REFERENCES "ExamType"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Result" ADD CONSTRAINT "Result_courseId_fkey" FOREIGN KEY ("courseId") REFERENCES "Course"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Result" ADD CONSTRAINT "Result_enteredBy_fkey" FOREIGN KEY ("enteredBy") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Result" ADD CONSTRAINT "Result_verifiedBy_fkey" FOREIGN KEY ("verifiedBy") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
