// app/api/academic-calendar/route.js

import { NextResponse } from 'next/server';
import prisma from '@/lib/prisma';

// GET: Fetch calendar events
export async function GET(request) {
  try {
    const { searchParams } = new URL(request.url);
    const startDate = searchParams.get('startDate');
    const endDate = searchParams.get('endDate');
    const batchId = searchParams.get('batchId');
    const limit = parseInt(searchParams.get('limit')) || 100;

    // Build where clause
    const where = {};

    if (startDate && endDate) {
      where.date = {
        gte: new Date(startDate + 'T00:00:00.000Z'),
        lte: new Date(endDate + 'T23:59:59.999Z'),
      };
    }

    if (batchId) {
      where.batchId = parseInt(batchId);
    }

    const events = await prisma.academicCalendar.findMany({
      where,
      orderBy: {
        date: 'asc',
      },
      take: limit,
      include: {
        batch: {
          select: {
            id: true,
            name: true,
          },
        },
        notices: true,
      },
    });

    return NextResponse.json({ 
      success: true, 
      events, 
      count: events.length 
    });
    
  } catch (error) {
    console.error('Error fetching calendar events:', error);
    return NextResponse.json(
      { 
        error: 'Failed to fetch calendar events', 
        details: error.message,
        code: error.code || 'UNKNOWN_ERROR'
      },
      { status: 500 }
    );
  }
}

// POST: Create a new calendar event
export async function POST(request) {
  try {
    const body = await request.json();
    
    const {
      date,
      description,
      eventType,
      semester,
      batchId,
      isAutoGenerated,
      isTermExam,
    } = body;

    // Validate required fields
    if (!date || !description || !eventType) {
      return NextResponse.json(
        { error: 'Missing required fields: date, description, eventType' },
        { status: 400 }
      );
    }

    // Check for duplicate event
    const existingEvent = await prisma.academicCalendar.findFirst({
      where: {
        date: new Date(date + 'T00:00:00.000Z'),
        eventType: eventType,
        batchId: batchId ? parseInt(batchId) : null,
      },
    });

    if (existingEvent) {
      return NextResponse.json(
        { 
          error: 'Duplicate event', 
          message: 'An event with this date and type already exists',
          existing: existingEvent 
        },
        { status: 409 }
      );
    }

    // Create the event
    const event = await prisma.academicCalendar.create({
      data: {
        date: new Date(date + 'T00:00:00.000Z'),
        description,
        eventType,
        semester: semester || null,
        batchId: batchId ? parseInt(batchId) : null,
        isAutoGenerated: isAutoGenerated || false,
        isTermExam: isTermExam || false,
      },
      include: {
        batch: {
          select: {
            id: true,
            name: true,
          },
        },
        notices: true,
      },
    });

    return NextResponse.json(
      { success: true, event, message: 'Event created successfully' },
      { status: 201 }
    );
    
  } catch (error) {
    console.error('Error creating calendar event:', error);
    return NextResponse.json(
      { 
        error: 'Failed to create calendar event', 
        details: error.message,
        code: error.code || 'UNKNOWN_ERROR'
      },
      { status: 500 }
    );
  }
}

// PUT: Update an existing calendar event
export async function PUT(request) {
  try {
    const body = await request.json();
    const { id, date, description, eventType, semester, batchId, isAutoGenerated, isTermExam } = body;

    if (!id) {
      return NextResponse.json(
        { error: 'Missing required field: id' },
        { status: 400 }
      );
    }

    // Check if event exists
    const existingEvent = await prisma.academicCalendar.findUnique({
      where: { id: parseInt(id) },
    });

    if (!existingEvent) {
      return NextResponse.json(
        { error: 'Event not found' },
        { status: 404 }
      );
    }

    // Update the event
    const updatedEvent = await prisma.academicCalendar.update({
      where: { id: parseInt(id) },
      data: {
        date: date ? new Date(date + 'T00:00:00.000Z') : undefined,
        description: description || undefined,
        eventType: eventType || undefined,
        semester: semester || null,
        batchId: batchId ? parseInt(batchId) : null,
        isAutoGenerated: isAutoGenerated !== undefined ? isAutoGenerated : undefined,
        isTermExam: isTermExam !== undefined ? isTermExam : undefined,
      },
      include: {
        batch: {
          select: {
            id: true,
            name: true,
          },
        },
        notices: true,
      },
    });

    return NextResponse.json(
      { success: true, event: updatedEvent, message: 'Event updated successfully' }
    );
    
  } catch (error) {
    console.error('Error updating calendar event:', error);
    return NextResponse.json(
      { 
        error: 'Failed to update calendar event', 
        details: error.message,
        code: error.code || 'UNKNOWN_ERROR'
      },
      { status: 500 }
    );
  }
}

// DELETE: Delete a calendar event
export async function DELETE(request) {
  try {
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');

    if (!id) {
      return NextResponse.json(
        { error: 'Missing required parameter: id' },
        { status: 400 }
      );
    }

    // Check if event exists
    const existingEvent = await prisma.academicCalendar.findUnique({
      where: { id: parseInt(id) },
      include: { notices: true },
    });

    if (!existingEvent) {
      return NextResponse.json(
        { error: 'Event not found' },
        { status: 404 }
      );
    }

    // Delete all associated notices first
    if (existingEvent.notices && existingEvent.notices.length > 0) {
      await prisma.calendarNotice.deleteMany({
        where: { calendarId: parseInt(id) },
      });
    }

    // Delete the event
    await prisma.academicCalendar.delete({
      where: { id: parseInt(id) },
    });

    return NextResponse.json(
      { success: true, message: 'Event deleted successfully' }
    );
    
  } catch (error) {
    console.error('Error deleting calendar event:', error);
    return NextResponse.json(
      { 
        error: 'Failed to delete calendar event', 
        details: error.message,
        code: error.code || 'UNKNOWN_ERROR'
      },
      { status: 500 }
    );
  }
}